services:
  - type: web
    name: n8n-free
    env: node
    plan: free
    region: frankfurt  # or your nearest Render region
    buildCommand: npm install --legacy-peer-deps
    startCommand: npx n8n start
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
      - key: GENERIC_TIMEZONE
        value: Europe/Istanbul
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: db.fhczcacmiohsszktjiyx.supabase.co
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PASSWORD
        value: Vr6WHpPVUZ3*btJ
      - key: N8N_ENCRYPTION_KEY
        value: 18n2b27ya789dwl6hns23h75ge65w6bp
      - key: N8N_BASIC_AUTH_ACTIVE
        value: 'true'
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: adnaninoksan
